name: Daily Finance Dashboard

on:
  schedule:
    - cron: "0 12 * * *"  # 12:00 UTC = 8 AM ET
  workflow_dispatch:     # also allow manual run

jobs:
  run-dashboard:
    runs-on: ubuntu-latest
    env:
      SMTP_SERVER: ${{ secrets.SMTP_SERVER }}
      SMTP_PORT: ${{ secrets.SMTP_PORT }}
      YOUR_EMAIL: ${{ secrets.YOUR_EMAIL }}
      YOUR_APP_PASSWORD: ${{ secrets.YOUR_APP_PASSWORD }}
      MAIN_RECIPIENT: ${{ secrets.MAIN_RECIPIENT }}
      RECIPIENTS_EMAIL: ${{ secrets.RECIPIENT_EMAIL }}
      NEWS_API_KEY: ${{ secrets.NEWS_API_KEY }}
      OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Run dashboard
        run: |
          python main.py
